### ISSUE TITLE
Oauth error when trying to add Gmail account

### ISSUE THREAD

**Issue by mateusfccp** [Eppie-io/Eppie-CLI#158]
**Describe the bug**
When trying to add Gmail account, I get an Oauth error.

**To Reproduce**
1. Start the Eppie cli
2. Open the vault
3. Try to add an account with `add-account -t Email`
4. When prompted to select the e-mail type, select `1) Gmail`
5. An authentication prompt will be open in the browser, but with an Oauth error

**Expected behavior**
The account should be authenticated.

**Screenshots**
<img width="472" alt="image" src="https://github.com/Eppie-io/Eppie-CLI/assets/4605213/d2ca48d7-a5f7-48a8-bbda-c825fbc55894">

The screenshot has some parts in portuguese, which translates as follow:
* Title: Access blocked: authorization error
* First blue link: Know more about the error
* Last text: If you are one of the developers of this app, check the errors details.

<img width="358" alt="image" src="https://github.com/Eppie-io/Eppie-CLI/assets/4605213/9b9a334b-22de-468d-9fbd-1f7e9ea76466">

The entire text is:

Detalhes da solicitação: redirect_uri=http%3A%2F%2F127.0.0.1%3A64112%2F

The part in portuguese in this second screenshot means "Request details:".

**Desktop:**
 - OS: macOS Sonoma 14.4.1 (23E224)
 - Browser: Firefox
 - Version 126.0 (64-bit)

**Additional details:**
The documentation linked in the error message is the following: https://developers.google.com/identity/protocols/oauth2/policies#secure-response-handling

**Comment by ValeraFinebits** [comment]
The bug with Google authentication is now fixed. 
With that said, to authorize Eppie at Gmail at the moment you need to create your own application credentials in [Google Cloud Platform](
https://console.cloud.google.com/) as described [here](
https://github.com/Eppie-io/Eppie-CLI/blob/main/docs/Register%20the%20application.md).
Then pass the created **Client ID** and **Client Secret** as arguments when launching Eppie-CLI — [here](
https://github.com/Eppie-io/Eppie-CLI/blob/main/README.md#Launch)
is the sample command.
