### ISSUE TITLE
Proton Mail account password is rejected

### ISSUE THREAD

**Issue by ValeraFinebits** [Eppie-io/Eppie-CLI#220]
**Describe the bug**
Proton Mail account password is rejected when attempting to log in via the app, despite being correct.

**To Reproduce**
1. Open the Eppie-CLI app.
2. Attempt to link a Proton Mail account.
3. Enter the correct Proton Mail account email and password.
See error message:
"Proton: failed to login. Reason: Proof cannot not be calculated. Some data is corrupted or missing."

**Expected behavior**
The app should accept the correct Proton Mail account password and successfully log in.

**Additional context**
The issue seems to be related to the use of very long passwords > 71 symbols.

**Comment by al-kau** [comment]
There is a limitation for the password inside **The Bouncy Castle Cryptography library** 
file: [BCrypt.cs](https://github.com/bcgit/bc-csharp/blob/release/v2.4/crypto/src/crypto/generators/BCrypt.cs#L617)
method: **‎BCrypt::Generate**

**Comment by al-kau** [comment]
I didn't find any password limitations in the [protonmail bcrypt](https://github.com/ProtonMail/bcrypt) library.
file: bcrypt.go; function: [HashBytes](https://github.com/ProtonMail/bcrypt/blob/master/bcrypt.go#L110)
file: cipher.go; function: [crypt_raw](https://github.com/ProtonMail/bcrypt/blob/master/cipher.go#L390)
